services:
  postgres:
    image: postgres:16
    container_name: instaclone_postgres
    environment:
      POSTGRES_DB: instacloneDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rahul5264
    ports:
      - "5435:5432"
    volumes:
      - instaclone_data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: instaclone_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2182:2182"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: instaclone_kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2182
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9093:9093"

  app:
    build: .
    container_name: instaclone_app
    depends_on:
      - postgres
      - kafka
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: rahul5264
      NEO4J_HOST: host.docker.internal
      KAFKA_HOST: kafka
      JWT_SECRET: ${JWT_SECRET}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
    ports:
      - "8081:8081"

volumes:
  instaclone_data: